### ISSUE TITLE
whirlgif collision with FSL?

### ISSUE THREAD

**Issue by TheChymera** [afniHQ/AFNI#6]
As stated in a previoeus issue, I am trying to build AFNI for Gentoo. This is starting to look better and better and stuff kind-of works now. But, I get a file collision with FSL for `/usr/bin/whirlgif`. This means that both AFNI and FSL are trying to include a binary with the same name. 

* Is this an AFNI file that FSL also likes to ship?
* Is this an FSL file that AFNI also likes to ship?
* Are these two rather different files which happen to have the same name?

I checked, and the two binaries have different checksums - but I guess this is expected anyway...

**Comment by TheChymera** [comment]
Ok, judging by a diff of the sources, it looks like FSL's version is newer (additional copyright note from 1999 compared to AFNI). I'd hazard a guess that FSL happens to ship an updated version of a file with essentially the same functionality (though the code looks quite different). IS this corrct? Any ideas if the 1999 revision is backwards-compatible? any particular reason you do not use the newer version?

**Comment by afni-rwcox** [comment]
Yes, there is a reason.  Whirlgif in AFNI is used to write animated GIFs from the interface.  That is it's only function, and the version we have works for that purpose.  I see no reason to put any effort at all into including a later edition of the program in our software.

**Comment by TheChymera** [comment]
OK, fair enough. What would AFNI do if it did not find the binary, or if the binary would throw an error or return improper output? Just a graphic glitch or would the AFNI GUI crash?

**Comment by afni-rwcox** [comment]
Here is how it works:

(a) AFNI searches the PATH for an executable named ppmtogif
(b) if that fails, then GIF output (single image or animated) is disabled
(c) otherwise, AFNI searches the PATH for a executable named gifsicle
(d) if that fails, it searches the PATH for an executable named whirlgif
(e) if both gifsicle and whirlgif searches fail, then AFNI will not create the button that allows the user to write out animated GIFs
(f) otherwise, the button is created and the external program is used (with appropriate options) to create the animated GIF when the user clicks the button

The AFNI GUI seldom crashes any more -- we've wrung out most of the bugs.  Of course, having said that means that it will crash about 7 minutes from now.

If the updated whirlgif is command-line compatible with the older one, then AFNI should work with it, even if it isn't the one AFNI installs.  But from the above, you can actually see that whirlgif is just the backup if gifsicle isn't available.  I can't really recall why I replaced whirlgif usage with gifsicle -- I think the latter program had some option I liked that whirlgif didn't have -- but that was a long time ago (2001 by my log of program changes http://afni.nimh.nih.gov/pub/dist/doc/program_help/history_all.html )

**Comment by nno** [comment]
@TheChymera is this still an issue?

Since the official AFNI is now hosted at https://github.com/afni/afni, we would like to close down afniHQ entirely. If this is still an issue, can you please re-open at https://github.com/afni/afni?

**Comment by nno** [comment]
Thanks @TheChymera for your quick response.
